# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: php build.php
      - run:
        command: |
          git config user.email "azureci@pivvenit.net"
          git config user.name "Azure Pipelines Bot"
          git status
          if [[ -n $(git status -s) ]]
          then
            git add -A
            git stash
            git checkout gh-pages
            git checkout stash -- composer
            git commit -m "***NO_CI*** Update packages"
            git push https://$(pat)@github.com/pivvenit/acf-composer-bridge.git
          else
            echo "No changes in the repository"
          fi