version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run:
          name: Generate repository
          command: php build.php
      - run:
          name: Deploy to github pages
          command: |
            git config user.email "azureci@pivvenit.net"
            git config user.name "Azure Pipelines Bot"
            git status
            if [[ -n $(git status -s) ]]
            then
              git add -A
              git stash
              git checkout gh-pages
              git checkout stash -- composer
              git commit -m "[skip ci] Update packages"
              git push https://$(pat)@github.com/pivvenit/acf-composer-bridge.git
            else
              echo "No changes in the repository"
            fi